graph TD 
  Tramadol -- develops into --> opioid 
  opioid -- regulates --> chronic_pain 
  chronic_pain -- enhances --> pain_relief 
  pain_relief -- causes --> side_effects 
  side_effects -- influences --> cardiac_complications
