graph TD 
  chronic_food_insecurity -- influences --> transitory_food_insecurity 
  transitory_food_insecurity -- influences --> trade_liberalization 
  trade_liberalization -- develops into --> 2002_food_crisis_in_Southern_Africa 
  2002_food_crisis_in_Southern_Africa -- develops into --> food_security 
  food_security -- supports --> World_Food_Summit_(WFS)
