graph TD 
  Heidi_Newberg -- is part of --> Rensselaer_Polytechnic_Institute 
  Rensselaer_Polytechnic_Institute -- supports --> Frontiers_in_Astronomy_and_Space_Science 
  Frontiers_in_Astronomy_and_Space_Science -- influences --> Earth_2.0 
  Earth_2.0 -- supports --> habitable_worlds 
  habitable_worlds -- supports --> rectangular_mirror
