graph TD 
  recombinant_zoster_vaccine -- reduces --> RZV 
  RZV -- regulates --> live_zoster_vaccine 
  live_zoster_vaccine -- enhances --> herpes_zoster 
  herpes_zoster -- is part of --> shingles 
  shingles -- develops into --> postherpetic_neuralgia
