graph TD
    Sustainable_agriculture --> Ecosystem_services
    Ecosystem_services --> Climate_change
    Climate_change --> Water_scarcity
    Water_scarcity --> Water_pollution
    Water_pollution --> Land_degradation
