graph TD 
    Men -- related_to --> women 
    women -- related_to --> brains 
    brains -- related_to --> Alzheimer_disease 
    Alzheimer_disease -- related_to --> ageing 
    ageing -- related_to --> brain_volume_reduction
