graph TD 
    auditory_task_switching -- related_to --> response_set_overlap 
    response_set_overlap -- related_to --> task_preparation 
    task_preparation -- related_to --> cued_auditory_task_switching 
    cued_auditory_task_switching -- related_to --> pitch 
    pitch -- related_to --> loudness