graph TD 
    Heidi_Newberg -- related_to --> Rensselaer_Polytechnic_Institute 
    Rensselaer_Polytechnic_Institute -- related_to --> Frontiers_in_Astronomy_and_Space_Science 
    Frontiers_in_Astronomy_and_Space_Science -- related_to --> Earth_2.0 
    Earth_2.0 -- related_to --> habitable_worlds 
    habitable_worlds -- related_to --> rectangular_mirror