graph TD 
    chronic_food_insecurity -- related_to --> transitory_food_insecurity 
    transitory_food_insecurity -- related_to --> acute_food_insecurity 
    acute_food_insecurity -- related_to --> food_security 
    food_security -- related_to --> household_food_security 
    household_food_security -- related_to --> food_crisis