graph TD 
    Tramadol -- related_to --> opioid 
    opioid -- related_to --> chronic_pain 
    chronic_pain -- related_to --> pain_relief 
    pain_relief -- related_to --> serious_side_effects 
    serious_side_effects -- related_to --> cardiac_complications