graph TD 
    Hanle -- related_to --> Ladakh 
    Ladakh -- related_to --> Tsering_Dolkar 
    Tsering_Dolkar -- related_to --> Venus 
    Venus -- related_to --> Milky_Way 
    Milky_Way -- related_to --> Indian_Astronomical_Observatory