graph TD 
    recombinant_zoster_vaccine_(RZV) -- related_to --> herpes_zoster_(shingles) 
    herpes_zoster_(shingles) -- related_to --> postherpetic_neuralgia 
    postherpetic_neuralgia -- related_to --> ophthalmicus 
    ophthalmicus -- related_to --> immunocompromised_status 
    immunocompromised_status -- related_to --> CDC